# Generated by Django 5.0.4 on 2024-05-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_name', models.CharField(max_length=20)),
                ('Emp_age', models.IntegerField()),
                ('Salary', models.IntegerField()),
            ],
        ),
    ]
